apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-dev
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 12
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: busybox
        # image: smlabs.azurecr.io/customsmetrics:latest

        ports:
        - containerPort: 8080
