apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-development
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 10
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: smlabs.azurecr.io/argocd-app
        # image: smlabs.azurecr.io/customsmetrics:latest

        ports:
        - containerPort: 8080
